<?php include 'header.php';?>
        
<div id="main" class="main-block main-block_v2">
  <noscript>
    <div class="wrapper"><p class="javascript-error">Descargar videos de facebook utiliza Javascript para la visualización de algunos contenidos. Habilite Javascript en su navegador y vuelva a cargar esta página.</p></div>
  </noscript>
    <!--content-->
    <div class="wrapper">

        <article class="article-1" dir="ltr">
<h1 class="center small-caps">DESCARGAR VIDEOS DE FACEBOOK PRIVACY POLICY</h1>

<p><strong>PLEASE READ THIS DOCUMENT CAREFULLY. IT CONTAINS IMPORTANT INFORMATION THAT YOU SHOULD KNOW BEFORE USING THE WEBSITE OR SERVICES. BY USING THE WEBSITE OR SERVICES, YOU WILL BE DEEMED TO HAVE ACCEPTED THIS PRIVACY POLICY.</strong></p>

<p>By using the Website or Services, you accept the practices set forth in this Privacy Policy and the <a href="terms.php">Terms of Service</a>. This privacy statement was last updated on <strong>March 10, 2020</strong>. This privacy statement was created in order to disclose its information gathering and dissemination practices for its website located at <a href="https://Descargarvideosdefacebook.vertiens.com"> Descargarvideosdefacebook.vertiens.com </a> and other related websites owned and/or operated by Descargar vidoes de facebook (together, the "Website"), products (for example, Descargar vidoes de facebook Net Helper), and the services offered and provided through the Website (the <strong>"Services"</strong> as described in the <a href="terms.php">Terms of Service</a>). </p>
<p>We have created this privacy statement in order to provide you with clear, simple and complete information about how we process the personal data you give us or the data we may collect while you are browsing our website, how it may be transferred to third parties and your rights and options to control your personal information and protect your privacy. Accordingly, we prepared this statement to inform you of the privacy principles that govern the Website and Services (the <strong>"Privacy Policy"</strong>). </p>
<p>Descargar vidoes de facebook reserves the right to modify this Privacy Policy at any time by posting such changes on this page. If we make any material changes we will notify you by means of a notice on the Website prior to the change becoming effective, and we may also try to notify you through email of the privacy changes, if necessary. Please check the revision date below to determine if this Privacy Policy has been modified since you last reviewed it. Your continued use of any portion of the Website or Services following posting of the updated Privacy Policy will constitute your acceptance of the changes.</p>
<p><strong>A. INFORMATION WE COLLECT</strong></p>
<p><strong>How we collect your information</strong></p>
<p>We may collect information regarding the use of our Website, especially with respect to your browsing (pages visited, links clicked, etc.). Some of this information may be collected using cookies placed in your web browser when you browse our website. The information that we request is and will be retained by us and used as described in this Privacy Policy. We do not request or intend to collect any &ldquo;special categories of information&rdquo; such as any information on health, race, religion, political opinions or philosophical beliefs, sexual preferences or orientation.</p>
<p>When you request a page from our Website, our servers log the information provided in the HTTP request header, JavaScript or similar technical tools, including the IP number, the time of the request, the URL of your request and other information. We collect this information in order to make our Website function correctly and provide you the functionality that you see on the Website, as our servers use this information to deliver to you the pages on this Website. We also use this information to better understand how visitors use our Website and how we can better tune our Website, its contents and functionality to meet your needs. However, this information is not associated with any personally identifiable information of persons browsing the Website.</p>
<p>When you use the Website, Descargar vidoes de facebook or trusted third parties authorized by Descargar vidoes de facebook may also collect certain technical and routing information about your computer (also known as environmental variables) to facilitate your use of the Website and the Services enabled thereby. When you browse the Internet, your Internet browser (such as Mozilla Firefox, Google Chrome, or Microsoft Internet Explorer) automatically transmits some information to Descargar vidoes de facebook every time you access content on one of our internet domains. Examples of such information include the URL of the particular Web page you visited, the IP (Internet Protocol) address of the computer you are using, or the browser version that you are using to access the Website. All of this information may be collected by Descargar vidoes de facebook and used to help improve our offerings to you.</p>
<p>We use cookies and other similar technologies to help provide our Services, to advertise to you and to analyse how you use our Services and whether advertisements are being viewed. By continuing to use and navigate our sites, services, applications, tools or messaging, you are agreeing to our use of cookies of described in this Privacy Policy.</p>
<p>Descargar vidoes de facebook does not track users over time and across third party websites to provide targeted advertising and therefore does use do not track (DNT) signals. However, some third party sites may keep track of your browsing activities when they serve you content, which enables them to tailor what they present to you. If you are visiting such sites, your web browser may allow you to set the DNT signal on your browser so that third parties (particularly advertisers) know you do not want to be tracked.</p>
<p>Our Website also may contain links to other third-party websites. Descargar vidoes de facebook is not responsible for the privacy practices or the content of such websites. We encourage you to carefully read the privacy statement of any website you visit. Descargar vidoes de facebook may make third party applications available to you through the Website or Services. The information collected by Descargar vidoes de facebook when you enable a third party application is processed under this Privacy Policy. Information collected by the third party application provider is governed by the provider's privacy policies.</p>
<p><strong>We may collect your information when you:</strong><br>
(i) create a customer account on our applications, if applicable;<br>
(ii) contact our customer service or send requests for information to us;<br>
(iii) browse on the Internet using cookies or similar technology.</p>
<p><strong>Descargar vidoes de facebook processes your information to:</strong></p>
<ul>
  <li>enable you to create and manage your access to your customer account if applicable;</li>
  <li>connect you to external, third party applications, such as when you create an account using an external application;</li>
  <li>manage customer relations with respect to any requests for information or complaints you may send us;</li>
  <li>manage and optimize your customer experience by improving our knowledge of our customers;</li>
  <li>conduct statistical analyses to develop management, measuring and reporting tools in order to adjust and improve our services;</li>
  <li>when you have given your consent for the processing of your data and of your browsing data via cookies, etc.</li>
</ul>
<p><strong>User Account</strong></p>
<p>Some of the Services offered to users of the Website may require you to register for a user account with Descargar vidoes de facebook (<strong>"User Account"</strong>). When registering for a User Account, Descargar vidoes de facebook will ask you to voluntarily supply Descargar vidoes de facebook with certain information about yourself. You may also register with Descargar vidoes de facebook through your account with certain third party social networking services (collectively, <strong>"SNS"</strong>). Please note that if you opt to use your SNS account to login to our Website and use our Services, Descargar vidoes de facebook is able to access your data in connection with your SNS account. If you wish to deactivate your personal User Account, you can contact us at <a href="mailto:support@vertiens.com"> support@vertiens.com</a>.   When you deactivate your personal account, all information stored and maintained as part of your account, including, without limitation information obtained from your SNS will be deactivated (although some information may be retained for archival, analytics, backup and record purposes). </p>
<p><strong>Information Relating to Children</strong></p>
<p>The Descargar vidoes de facebook Website and any Software or Services available on that site are not directed at children under 16 years or other permitted by the applicable law age. However, we recognize that children under the permitted age may access this Website and subscribe to the newsletter, purchase Software and Services, or download software programs. The collection of information is covered above. Parents and Legal Guardians may request from us to review, delete or stop the collection of the personally identifiable information of their child. You may do so by contacting us by letter or email to <a href="mailto:support@vertiens.com"> support@vertiens.com</a>.  </p>
<p><strong>B. COOKIE POLICY</strong></p>
<p><strong>Cookies and Web Beacons</strong></p>
<p>The Website uses "cookie" and "web beacon" technology. Cookies are tiny text files that are stored on our website as you browse, to help track your use of our site and to personalize your journey. If you return to the website, the server can call the information from the cookies stored on your computer to tailor your experience of the site. Web beacons are used in combination with cookies to help website operators understand how visitors interact with their websites. A web beacon is typically a transparent graphic image (usually 1 pixel x 1 pixel) that is placed on a site. As opposed to cookies, which are stored on a user's computer hard drive, web beacons are embedded invisibly on Web pages and are about the size of the period at the end of this sentence. The use of a web beacons allows the site to measure the actions of the visitor opening the page that contains the web beacon. It makes it easier to follow and record the activities of a recognized browser, such as the path of pages visited at a website. Descargar vidoes de facebook uses the information provided by web beacons to develop a better understanding of how the Website's visitors use the Website, and to facilitate those visitors' interactions with the Website. </p>
<p>We want to make sure you are fully aware of the cookies we use and what they do on Descargar vidoes de facebook. Our cookies serve various purposes, but are generally either necessary or essential to the functioning of our sites, services, applications, tools or messaging, help us improve the performance or provide you extra functionality of the same, or help us to serve relevant and targeted advertisements. Cookies can be categorized by the purpose they serve and by whether they are considered a &ldquo;First Party Cookie&rdquo; or &ldquo;Third Party Cookie,&rdquo; which describes who manages and controls the cookie and any information it collects.</p>
<p><strong>First Party Cookies.</strong> These are cookies that are controlled and managed by Descargar vidoes de facebook. This means that we also have access to any data that is being collected or stored. Descargar vidoes de facebook only uses First Party Cookies that are either Strictly Necessary.</p>
<p><strong>Third Party Cookies. </strong>These are cookies that are controlled and managed by a third party and they place these cookies on your device when you visit our site. Data collected, stored or used by the cookie is only accessible by the third party. We may use Third Party Cookies for each of the purposes listed below. Some may collect personally identifiable information (such as IP addresses). Some collect data in an anonymized form and aggregate statistics (such as Performance Cookies.)</p>
<p>Please note that Third Party Cookies, which include the use of cookies by our partners, affiliates and service providers, are not covered by our privacy statement. We do not have access to or control over these cookies. In addition, Descargar vidoes de facebook does not have access to any cookie-specific information collected directly by Third Party Cookies. To obtain access to or review your cookie-specific information, you will need to contact the third party as they control the cookie(s). These cookies are not essential to browsing on our website. </p>
<p><strong>"Essential" </strong>cookies are essential for browsing on our website, especially for the functioning of the order process. Deletion of these cookies may cause problems with browsing on our website.</p>
<p><strong>"Analysis and Customization" </strong>cookies are not essential to browsing on our website, but may help you, for example, to search more effectively and optimise your purchasing experience and help us better target your requirements, improve our offer and optimise the functioning of our website.</p>
<p><strong>&ldquo;Functional&rdquo;</strong> cookies are used to provide services or to remember settings to improve your visit. They may be set by us or by third party providers whose services we have added to our pages.</p>
<p><strong>&ldquo;Performance&rdquo;</strong> cookies do not collect any information that could identify you and are only used to help us improve how our website works, understand what interests our users and measure the effectiveness of our content. They do this by gathering statistical information, for instance, about page visits and traffic sources so we can measure and improve the performance of our site. This also helps us know which pages are the most and least popular and lets us understand how visitors more around the site. The statistical data collected by these cookies is aggregated and anonymous.</p>
<p><strong>&ldquo;Targeting&rdquo;</strong> cookies may be set through our sites, applications, or tools by third party advertising partners. This is in order to deliver content, including product related advertisements, relevant to your specific interests on our sites or third-party sites. They may be used by these companies to build a profile of your interests so that relevant adverts can be displayed on other sites. The profiles are built based on a unique identifier that is assigned to the cookie and linked to your browser and internet device.</p>
<p>You can set your browser software so that you are regularly asked if you wish to accept or refuse cookies before a cookie can be registered; you systematically refuse the registration of cookies. Settings vary from one type of browser software to another. Details can generally be found in your browser software help menu. We therefore encourage you to look at your settings to find out how you can make choices regarding cookies. </p>
<p><strong>For Internet Explorer: </strong> <a href="https://support.microsoft.com/help/17442/windows-internet-explorer-delete-manage-cookies" rel="nofollow">https://support.microsoft.com/help/17442/windows-internet-explorer-delete-manage-cookies</a></p>
<p><strong>For Safari: </strong> <a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471" rel="nofollow">https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471</a></p>
<p><strong>For Chrome:</strong> <a href="https://support.google.com/chrome/answer/95647" rel="nofollow">https://support.google.com/chrome/answer/95647</a></p>
<p><strong>For Firefox:</strong> <a href="https://support.mozilla.org/kb/enable-and-disable-cookies-website-preferences" rel="nofollow">https://support.mozilla.org/kb/enable-and-disable-cookies-website-preferences</a></p>
<p><strong>For Opera:</strong> <a href="https://www.opera.com/help/tutorials/security/privacy/" rel="nofollow">https://www.opera.com/help/tutorials/security/privacy/</a></p>
<p>Any adjustments you may make to the settings in your browser software concerning the acceptance or refusal of cookies may modify your browsing on the Internet and your terms of access to certain services requiring use of these cookies. If you choose to refuse the use of cookies or if you delete cookies that are already registered, we decline all responsibility for any consequences relating to the degraded performance of our Services resulting from the fact we are unable to register or consult the cookies required for their performance and which you have refused or deleted.</p>
<p><strong>C. USE AND DISCLOSURE OF INFORMATION</strong></p>
<p><strong>We use your information for the following purposes</strong></p>
<p><strong>Delivering and improving our services. </strong>We use your information for developing, delivering and improving our Service, providing updates, technical troubleshooting, understanding and analyzing trends in connection with usage of the Services.</p>
<p><strong>Displaying advertisements</strong>. We may use your information for displaying third-party advertisements to make our Services available for free. </p>
<p><strong>Cross-promotion.</strong> We may use your information for cross-promoting our Services.</p>
<p><strong>Tracking and fraud prevention for advertising purposes.</strong> Your information is used for tracking how our advertising campaigns perform and for identifying and preventing fraud for our advertising campaigns.</p>
<p><strong>Analytics and research. </strong>We use your information for understanding about the usage of the Services. We may also create reports and analysis for the purposes of research, for example to track potential problems or to test our new features connected with our Services.</p>
<p><strong>Security. </strong>We use your information for enhancing the safety and security of our Services.</p>
<p><strong>Customer Support.</strong> We use your information for providing customer support to you and to respond to your inquiries.</p>
<p><strong>Our legal obligations. </strong>We use your information when we are required to do so by law.</p>
<p><strong>How We Share This Information</strong></p>
<p>Descargar vidoes de facebook shares information within its affiliated brands and companies. We also share information we have about you for the purposes described in this Privacy Policy, including to provide Services that you have requested. We do not share information that individually identifies our customers with companies, organizations or individuals outside of Descargar vidoes de facebook, unless one of the following circumstances applies:</p>
<p><strong>Within Descargar vidoes de facebook. </strong>Information may also be shared within Descargar vidoes de facebook to provide support and delivery of Services we offer.</p>
<p><strong>With Partners.</strong> We may share aggregated or pseudonymous information with partners, such as measurement analytics, apps, or other companies. When you use third-party apps, websites or other products integrated with our Services, they may collect information about your activities subject to their own terms and privacy policies. When installing our browser extension &nbsp;Descargar vidoes de facebook Net Helper you agree that your data may be shared with third parties, according to the terms set forth in <a href="https://epolicyprotect.com/" rel="nofollow">their privacy policies</a>. If you want to withdraw your consent to share information while using our browser extension, please go the extension settings and switching off Web Statistic Tracker. </p>
<p><strong>For Legal and Other Purposes.</strong> We may access, preserve and disclose information to investigate, prevent, or take action in connection with legal process and legal requests, requests for customer service, technical issues or as otherwise required by law. </p>
<p><strong>New Ownership.</strong> If the ownership or control of all or part of Descargar vidoes de facebook or a specific Service changes as a result of a merger, acquisition or sale of assets, we may transfer your information to the new owner.</p>
<p><strong>Data Processing and Transfers</strong></p>
<p>Descargar vidoes de facebook operates secure data networks protected by industry standard firewall and password protection systems. Our security and privacy policies are periodically reviewed and enhanced as necessary, and only authorized individuals have access to the information provided by our users. Descargar vidoes de facebook takes steps to ensure that your information is treated securely and in accordance with this Privacy Policy. Because laws applicable to personal information vary by country, our offices or other business operations may put in place additional measures that vary depending on the applicable legal requirements. Your information is only accessible to those Descargar vidoes de facebook employees who need it in order to perform their jobs. Legal periods of retention of your personal information is defined by Descargar vidoes de facebook comply with the legal obligations covering Descargar vidoes de facebook.</p>
<p>When you submit personal information to Descargar vidoes de facebook through the Website, you understand and agree that this information may be transferred across national boundaries. In addition, you authorize Descargar vidoes de facebook to transfer, process, store and use your information in countries other than your own in accordance with this Privacy Policy and to provide you with Services. All data transfers are subject to appropriate guarantees, especially contractual, technical and organizational guarantees, that comply with applicable regulations relating to the protection of personal data.</p>
<p><strong>D. CHOICES AVAILABLE TO YOU</strong></p>
<p>You can always choose whether or not to disclose personally identifiable information and that choice will not prevent you from using the Website. Please note, however, if you should choose to withhold requested information, we may not be able to provide you with some of the Services dependent upon the collection of this information and you will be given an opportunity to "opt-in" and make your preference choices for any items that are optional and which are not prerequisite for our rendering such Services. </p>
<p>You can choose at any time to opt out of receiving emails from Descargar vidoes de facebook by clicking the unsubscribe link at the bottom of any email you receive from Descargar vidoes de facebook or by contacting Descargar vidoes de facebook directly at <a href="mailto:support@vertiens.com"> support@vertiens.com</a>.   We reserve the right to send a one-time registration confirmation email, and infrequent service alert messages to users to inform you of specific changes that may impact your ability to use a service that you have previously signed up for, regardless of email contact opt-in status. We also reserve the right to contact you if compelled to do so as part of a legal proceeding or if there has been a violation of any applicable licensing, warranty or agreements.</p>
<p>Descargar vidoes de facebook takes and addresses its users' privacy concerns with utmost respect and attention. You may have rights under the applicable laws to have access to your personal information and to ask us to rectify, erase and restrict the use of, your personal information. You may also have rights to object to your personal information being used, to ask for the transfer of personal information you have made available to us and to withdraw consent to the use of your personal information. You can exercise these rights directly with Descargar vidoes de facebook by submitting a request at <a href="mailto:support@vertiens.com"> support@vertiens.com</a>.  </p>
<p>If you have any questions about privacy and our data policies or believe that there was an instance of non-compliance with this Privacy Policy with regard to your personal information or you have other related inquiries or concerns, you may write or contact Descargar vidoes de facebook at email: <a href="mailto:support@vertiens.com"> support@vertiens.com</a>.  In your message, please describe in as much detail as possible the nature of your inquiry or the ways in which you believe that the Descargar vidoes de facebook&rsquo;s Online Privacy Policy has not been complied with. We will investigate your inquiry or complaint promptly.</p>
        </article>

    </div>
    <!--/content--></div> <!--/main-->


<!--Footer-->
<?php include 'footer.php';?>
